version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/webapp/
hooks:
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: ./codedeploy/afterinstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: ubuntu
  ValidateServer:
    - location: ./codedeploy/validateServer.sh
      timeout: 300
      runas: ubuntu