name: On Push - Build and Deploy WebApp
on: 
  push:
    branches:
      - 'master'
  pull_request:
  # workflow_dispatch:
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'       
    container:
      image: node:14.5.0-alpine
  
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: "npm install"
      - name: Run Tests
        run: "npm run test"
        
  build-webapp:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        appname: ['csye6225-webapp']
        deploy-group: ['csye6225-webapp-deployment']
        s3-bucket: ['codedeploy.jayashreepatel.me']
        s3-key: ['webapp-$GITHUB_SHA']
        region: ['us-east-1']

    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt install -y curl
          sudo apt-get install -y unzip
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{matrix.region}}
      - name: Push artifact to S3
        run: |
          aws deploy push \
          --application-name ${{ matrix.appname }} \
          --description "This is a revision for the ${{ matrix.appname }}-$GITHUB_SHA" \
          --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-key }}.zip
      - name: Deploy application on EC2
        run: |
          aws deploy create-deployment \
          --application-name ${{matrix.appname}} \
          --deployment-group-name ${{matrix.deploy-group}} \
          --description "Deploy application revision ${{ matrix.appname }}-$GITHUB_SHA" \
          --s3-location bucket=${{matrix.s3-bucket}},bundleType=zip,key=${{matrix.s3-key}}.zip
